#!######################################################################
#!#                          ZSH Specific                             ##
#!######################################################################
# Treat # as a comment even in interactive shell
setopt interactivecomments

# Enable colors
autoload -Uz colors && colors

# Example minimal prompt
PROMPT='%F{cyan}%n@%m%f %F{yellow}%~%f %# '

#!######################################################################
#!#                            Exports                                ##
#!######################################################################
printf "\033[0;35mExports:\033[0m \033[0;34m$HOME/go/bin\033[0m\n"

export PATH="$HOME/go/bin:$PATH"


#!#############################################################################
#!#                                Misc                                      ##
#!#############################################################################


test() {
    setopt localoptions interactivecomments  # allow # comments in interactive zsh

    printf "\033[0;31m3...\033[0m\n"; sleep 1
    printf "\033[1;33m2...\033[0m\n"; sleep 1
    printf "\033[0;32m1...\033[0m\n"; sleep 1

    printf "\033[0;35mTEST\033[0m\n"

    printf "Press Enter to Exit"
    read -r
}


#!#############################################################################
#!#                         RocketPowerInc Greeter                           ##
#!#############################################################################
printf "\033[0;35mRocketPowerInc Commands:\033[0m \033[0;34ma/goo/go-pwr\033[0m\n"



alias a="go-pwr"

# Function to launch latest go-pwr
function goo() {
    cd "$HOME" || return
    rm -rf go-pwr
    rm -f "$HOME/go/bin/go-pwr"

    git clone https://github.com/rocketpowerinc/go-pwr.git || return
    cd go-pwr || return

    go clean -modcache
    rm -f go.sum
    go mod tidy

    make install || return
    "$HOME/go/bin/go-pwr"
}